In [286]:
import numpy as np
import pandas as pd

In [287]:
dataset = pd.read_csv("C:/Users/MRINALIN PANIGRAHI/OneDrive/ROHNIT coding/data science/dataset/anime.csv")

In [288]:
dataset.head(5)

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [289]:
dataset.loc[0]["Title"]

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [290]:
def no_of_eps(text):
    pointer=0
    data=""
    for i in text:
        if i=="(":
            pointer=1
        if pointer==1:
            data=data+i
        if i==")":
            pointer=0
    numbers = ''.join(ch for ch in data if ch.isdigit())
    return numbers

In [291]:
dataset["eps"]=dataset["Title"].apply(no_of_eps).astype(int)
dataset.head(5)

   Rank                                              Title  Score  eps
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10

In [292]:
dataset["Time_Interval"] = dataset["Title"].str.split(")").str[1].str[:19]

In [293]:
# dataset["Title"].str.split("(").str[0].str[: dataset["Title"].str.find("(")-1]
dataset["Title"]=dataset["Title"].str.extract(r'^(.*?)\(')

In [294]:
dataset

    Rank  ...        Time_Interval
0      1  ...  Apr 2009 - Jul 2010
1      2  ...  Apr 2011 - Sep 2011
2      3  ...  Oct 2022 - Dec 2022
3      4  ...  Apr 2015 - Mar 2016
4      5  ...  Apr 2019 - Jul 2019
5      6  ...  Apr 2011 - Mar 2012
6      7  ...  Jan 2021 - Jan 2021
7      8  ...  Oct 2011 - Sep 2014
8      9  ...  Apr 2022 - Jun 2022
9     10  ...  Oct 2012 - Mar 2013
10    11  ...  Mar 2023 - May 2023
11    12  ...  Jan 1988 - Mar 1997
12    13  ...  Jul 2023 - Aug 2023
13    14  ...  Apr 2021 - Jun 2021
14    15  ...  Jan 2017 - Mar 2017
15    16  ...  Apr 2006 - Mar 2010
16    17  ...  Sep 2016 - Sep 2016
17    18  ...  Oct 2017 - Mar 2018
18    19  ...  Oct 2008 - Mar 2009
19    20  ...  Apr 2008 - Sep 2008
20    21  ...  Jul 2013 - Jul 2013
21    22  ...  Sep 2020 - Sep 2020
22    23  ...  Aug 2017 - Aug 2017
23    24  ...  Jul 2018 - Oct 2018
24    25  ...  Apr 2004 - Sep 2005
25    26  ...  Aug 2016 - Aug 2016
26    27  ...  Dec 2022 - Dec 2022
27    28  ...  Oct 2022 - Dec 2022
28    29  ...  Dec 2022 - Dec 2022
29    30  ...  Jan 2023 - Jun 2023
30    31  ...  Jul 2023 - Aug 2023
31    32  ...  Jan 2018 - Mar 2018
32    33  ...  Apr 2020 - Oct 2021
33    34  ...  Jan 2019 - Apr 2019
34    35  ...  Dec 2020 - Mar 2021
35    36  ...  Dec 2021 - Feb 2022
36    37  ...  Jan 2017 - Jan 2017
37    38  ...  Apr 2023 - Jun 2023
38    39  ...  Oct 2016 - Dec 2016
39    40  ...  Jul 2001 - Jul 2001
40    41  ...  Jul 2013 - Dec 2013
41    42  ...  Jan 2022 - Apr 2022
42    43  ...  Oct 2000 - Mar 2002
43    44  ...  Apr 1998 - Apr 1999
44    45  ...  Apr 2022 - Oct 2022
45    46  ...  Jul 2019 - Dec 2019
46    47  ...  Oct 2014 - Dec 2014
47    48  ...  Jan 2017 - Mar 2017
48    49  ...  Oct 2022 - Dec 2022
49    50  ...  Feb 1999 - Sep 1999

[50 rows x 5 columns]

In [295]:
from datetime import datetime

def count_months(date_range):
    start_str, end_str = date_range.split(" - ")
    start_date = datetime.strptime(start_str, "%b %Y")
    end_date = datetime.strptime(end_str, "%b %Y")
    months = (end_date.year - start_date.year) * 12 + (end_date.month - start_date.month)
    
    return months

In [296]:
dataset["no of months"]=dataset["Time_Interval"].apply(count_months)

In [297]:
dataset

    Rank  ... no of months
0      1  ...           15
1      2  ...            5
2      3  ...            2
3      4  ...           11
4      5  ...            3
5      6  ...           11
6      7  ...            0
7      8  ...           35
8      9  ...            2
9     10  ...            5
10    11  ...            2
11    12  ...          110
12    13  ...            1
13    14  ...            2
14    15  ...            2
15    16  ...           47
16    17  ...            0
17    18  ...            5
18    19  ...            5
19    20  ...            5
20    21  ...            0
21    22  ...            0
22    23  ...            0
23    24  ...            3
24    25  ...           17
25    26  ...            0
26    27  ...            0
27    28  ...            2
28    29  ...            0
29    30  ...            5
30    31  ...            1
31    32  ...            2
32    33  ...           18
33    34  ...            3
34    35  ...            3
35    36  ...            2
36    37  ...            0
37    38  ...            2
38    39  ...            2
39    40  ...            0
40    41  ...            5
41    42  ...            3
42    43  ...           17
43    44  ...           12
44    45  ...            6
45    46  ...            5
46    47  ...            2
47    48  ...            2
48    49  ...            2
49    50  ...            7

[50 rows x 6 columns]

In [298]:
dataset.to_csv("C:/Users/MRINALIN PANIGRAHI/OneDrive/ROHNIT coding/data science/dataset/anime_new.csv", index=False)