In [1]:
import numpy as np
import pandas as pd

## pd.Series

In [2]:
data = [120, 135, 150, 160, 175, 180, 200, 210]
labels=[i for i in range(1,len(data)+1)]
arr=np.array([10,20,30])
dic={1:10,2:20,3:30}

In [3]:
pd.Series(data,index=labels)

1    120
2    135
3    150
4    160
5    175
6    180
7    200
8    210
dtype: int64

In [4]:
pd.Series(dic)

1    10
2    20
3    30
dtype: int64

In [5]:
pd.Series(arr,index= [i for i in range(1, len(arr) + 1)])
pd.Series(arr,index=  range(1, len(arr) + 1))

1    10
2    20
3    30
dtype: int64

## dataframe

In [6]:
dataset = {
    "Name": ["Rahul", "Priya", "Amit", "Sneha", "Arjun"],
    "Age": [25, 30, 28, 32, 27],
    "City": ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai"],
    "Salary": [50000, 65000, 72000, 80000, 54000]
}
pd.DataFrame(dataset,index=range(1,len(dataset["Name"])+1))

    Name  Age       City  Salary
1  Rahul   25     Mumbai   50000
2  Priya   30      Delhi   65000
3   Amit   28  Bangalore   72000
4  Sneha   32  Hyderabad   80000
5  Arjun   27    Chennai   54000

In [7]:

dataset2 = {
    'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve', 'Frank'],
    'age': [28, 34, 29, 31, 26, 35],
    'city': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Miami'],
    'salary': [75000, 85000, 72000, 90000, 68000, 80000]
}

pd.DataFrame(dataset2,index=range(1,len(dataset2["name"])+1))

      name  age         city  salary
1    Alice   28     New York   75000
2      Bob   34  Los Angeles   85000
3  Charlie   29      Chicago   72000
4    Diana   31      Houston   90000
5      Eve   26      Phoenix   68000
6    Frank   35        Miami   80000

In [8]:
dataset3= [
    ['Alice', 28, 'New York', 75000],
    ['Bob', 34, 'Los Angeles', 85000],
    ['Charlie', 29, 'Chicago', 72000],
    ['Diana', 31, 'Houston', 90000],
    ['Eve', 26, 'Phoenix', 68000],
    ['Frank', 35, 'Miami', 80000]
]
df = pd.DataFrame(dataset3,index=range(1,len(dataset3)+1),columns=["Name", "Age", "City", "Salary"])
df

      Name  Age         City  Salary
1    Alice   28     New York   75000
2      Bob   34  Los Angeles   85000
3  Charlie   29      Chicago   72000
4    Diana   31      Houston   90000
5      Eve   26      Phoenix   68000
6    Frank   35        Miami   80000

adding and deleting  a column

In [9]:
df["kids"] = [0, 1, 2, 1, 0, 3]

In [10]:
df.drop(["City", "kids"], axis=1, inplace=False)
# inplace=False means it will not change the original dataframe, it will return a new dataframe without the "City" column. If inplace=True, it will modify the original dataframe and remove the "City" column permanently.
# inplace=True will change the original dataframe permanently, so use it with caution. If you want to keep the original dataframe and create a new one without the "City" column, use inplace=False.
# axis=1 means we want to drop a column, if axis=0, it means we want to drop a row. In this case, we want to drop the "City" column, so we use axis=1. If we wanted to drop a row, we would use axis=0 and specify the index of the row we want to drop.

      Name  Age  Salary
1    Alice   28   75000
2      Bob   34   85000
3  Charlie   29   72000
4    Diana   31   90000
5      Eve   26   68000
6    Frank   35   80000

selecting a row

In [11]:
df.loc[1:3, ["Name", "Salary"]]
# loc is used to access a group of rows and columns by labels or a boolean array. In this case, we are accessing rows 1 to 3 (inclusive) and the columns "Name" and "Salary". This will return a new dataframe with the selected rows and columns.

      Name  Salary
1    Alice   75000
2      Bob   85000
3  Charlie   72000

In [12]:
df.loc[:,["Name", "City"]]

      Name         City
1    Alice     New York
2      Bob  Los Angeles
3  Charlie      Chicago
4    Diana      Houston
5      Eve      Phoenix
6    Frank        Miami

In [13]:
df.iloc[0:3, 0:2]
# iloc is used to access a group of rows and columns by integer position.
#  In this case, we are accessing rows 0 to 2 (exclusive) and columns 0 to 1 (exclusive). 
# This will return a new dataframe with the selected rows and columns based on their integer position in the original dataframe.

      Name  Age
1    Alice   28
2      Bob   34
3  Charlie   29

conditional selection

In [14]:
df[(df["Age"] > 30) & (df["Salary"] > 80000)]

    Name  Age         City  Salary  kids
2    Bob   34  Los Angeles   85000     1
4  Diana   31      Houston   90000     1

finding the empty data

In [15]:
dataset4 = {
    "Name": ["Alice", None, "Charlie", "Diana", "Eve", None],
    "Age": [28, 34, None, 31, None, 35],
    "City": ["New York", "Los Angeles", "Chicago", None, "Phoenix", None],
    "Salary": [75000, None, 72000, 90000, None, 80000]}
df2=pd.DataFrame(dataset4,index=range(1,len(dataset4["Name"])+1))

In [16]:
df2.isna()

    Name    Age   City  Salary
1  False  False  False   False
2   True  False  False    True
3  False   True  False   False
4  False  False   True   False
5  False   True  False    True
6   True  False   True   False

In [17]:
df2.isnull().sum()

Name      2
Age       2
City      2
Salary    2
dtype: int64

In [18]:
df2.isnull().any()

Name      True
Age       True
City      True
Salary    True
dtype: bool

In [19]:
df2.dropna( thresh=3,inplace=False)
#thresh=3 means that we want to drop rows that have less than 3 non-null values. In this case, if a row has 2 or fewer non-null values, it will be dropped from the dataframe. If a row has 3 or more non-null values, it will be kept in the dataframe. The inplace=False argument means that the original dataframe will not be modified, and a new dataframe with the dropped rows will be returned. If inplace=True, the original dataframe would be modified and the dropped rows would be removed permanently.

      Name   Age      City   Salary
1    Alice  28.0  New York  75000.0
3  Charlie   NaN   Chicago  72000.0
4    Diana  31.0       NaN  90000.0

In [20]:
df2.fillna(value={"Name": "", "Age": 0, "City": " ", "Salary": 000},inplace=False)
#fillna is used to fill the missing values in a dataframe. In this case, we are filling the missing values in the "Name" column with an empty string, the "Age" column with 0, the "City" column with a space, and the "Salary" column with 000. The inplace=False argument means that the original dataframe will not be modified, and a new dataframe with the filled values will be returned. If inplace=True, the original dataframe would be modified and the missing values would be filled permanently.

      Name   Age         City   Salary
1    Alice  28.0     New York  75000.0
2           34.0  Los Angeles      0.0
3  Charlie   0.0      Chicago  72000.0
4    Diana  31.0               90000.0
5      Eve   0.0      Phoenix      0.0
6           35.0               80000.0

**merging joining and concatination**

In [21]:
df5 = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing"]
},index=range(1,6))
df6 = pd.DataFrame({
    "Emp_ID": [101, 102, 103, 106],
    "Salary": [50000, 60000, 70000, 80000],
    "Bonus": [5000, 6000, 7000, 8000]
},index=range(1,5))

In [22]:
pd.merge(df5, df6, on="Emp_ID", how="outer")

   Emp_ID     Name Department   Salary   Bonus
0     101    Alice         HR  50000.0  5000.0
1     102      Bob         IT  60000.0  6000.0
2     103  Charlie    Finance  70000.0  7000.0
3     104    Diana         IT      NaN     NaN
4     105      Eve  Marketing      NaN     NaN
5     106      NaN        NaN  80000.0  8000.0

In [23]:
pd.concat([df5, df6], axis=1)

   Emp_ID     Name Department  Emp_ID   Salary   Bonus
1     101    Alice         HR   101.0  50000.0  5000.0
2     102      Bob         IT   102.0  60000.0  6000.0
3     103  Charlie    Finance   103.0  70000.0  7000.0
4     104    Diana         IT   106.0  80000.0  8000.0
5     105      Eve  Marketing     NaN      NaN     NaN

In [24]:
df6=pd.DataFrame({"name":["Rahul", "Priya"]},index=range(1,3))
df7=pd.DataFrame({"score":[85,90]},index=range(2,4))

In [25]:
df6.join(df7, how="outer")

    name  score
1  Rahul    NaN
2  Priya   85.0
3    NaN   90.0